const express = require('express');
const {registerUser,loginUser,refreshAccessToken,logoutUser,forgotPassword,verifyOtp,resetPassword} = require("../../controllers/auth/authController");
const router = express.Router();
router.post("/register",registerUser);
router.post("/login",loginUser);
router.post("/refresh",refreshAccessToken);
router.post("/logout",logoutUser);
router.post("/forgot-password",forgotPassword);
router.post("/verify-otp",verifyOtp);
router.post("/reset-password",resetPassword);
module.exports = router;